// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwpsZvZh69j_pyevD8vc4_tYVis3zst3U',
    appId: '1:38956501945:web:7ff0e019ddff8eb8f54468',
    messagingSenderId: '38956501945',
    projectId: 'pizza-delivery-e36bb',
    authDomain: 'pizza-delivery-e36bb.firebaseapp.com',
    storageBucket: 'pizza-delivery-e36bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQh6eI8hkjtccVvXarIO6kLzwcg2YrGA',
    appId: '1:38956501945:android:9bbaff12b5f3d75df54468',
    messagingSenderId: '38956501945',
    projectId: 'pizza-delivery-e36bb',
    storageBucket: 'pizza-delivery-e36bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLkRo7SKGDDkddrG5fkNchUbOcjNJYx24',
    appId: '1:38956501945:ios:1035684e4b388506f54468',
    messagingSenderId: '38956501945',
    projectId: 'pizza-delivery-e36bb',
    storageBucket: 'pizza-delivery-e36bb.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLkRo7SKGDDkddrG5fkNchUbOcjNJYx24',
    appId: '1:38956501945:ios:302c2547b1998b7df54468',
    messagingSenderId: '38956501945',
    projectId: 'pizza-delivery-e36bb',
    storageBucket: 'pizza-delivery-e36bb.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
